apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: german-credit
spec:
  explainer:
    containers:
    - command:
      - python
      - -m
      - aifserver
      - --predictor_host
      - german-credit-predictor-default.default.svc.cluster.local
      - --model_name
      - german-credit
      - --feature_names
      - age
      - sex
      - credit_history=Delay
      - credit_history=None/Paid
      - credit_history=Other
      - savings=500+
      - savings=<500
      - savings=Unknown/None
      - employment=1-4 years
      - employment=4+ years
      - employment=unemployed
      - --label_names
      - credit
      - --favorable_label
      - "1"
      - --unfavorable_label
      - "2"
      - --privileged_groups
      - '{"age": 1}'
      - --unprivileged_groups
      - '{"age": 0}'
      image: ibmandrewbutler/aif-server:v3
      imagePullPolicy: Always
      name: kfserving-container
      resources:
        limits:
          cpu: "2"
          memory: 2Gi
        requests:
          cpu: "2"
          memory: 2Gi
  predictor:
    containerConcurrency: 0
    containers:
    - image: ibmandrewbutler/aif-server:predictor
      name: kfserving-container
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "1"
          memory: 2Gi