apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  default:
    predictor:
      logger:
          url: http://message-dumper.default/
          mode: all
      sklearn:
        storageUri: "gs://kfserving-samples/models/sklearn/iris"
